2019-11-10 01:15:00.060156467 +0100 CET [clock-1] 2019-11-25 15:31:32 ERROR    type=cron name=pc_test_new_log_system status=failed stacktrace=Traceback (most recent call last): ###   File "scripts/test_logs.py", line 12, in <module> ###     raise ApiTiteLiveException('Error getting TiteLive stocks for siret: 56347') ### connectors.api_titelive_stocks.ApiTiteLiveException: Error getting TiteLive stocks for siret: 56347 ###
